[[CURRENCIES]]
code="Zam"
issuer="GDRMTATDWU5IHUDJHYAIKZLDOCYQKR2TCOKWPBENZPPME5ZRMZQGGLRS"
display_decimals=4
name="Zam"
desc="Token of Zamzam - digital bank 3.0, blockchain powered"
conditions="There will only ever be 8,500,000,000 Zam tokens in existence."
image="https://zam.io/.well-known/logo.png"
