[[CURRENCIES]]
code="Zam"
issuer="GDRMTATDWU5IHUDJHYAIKZLDOCYQKR2TCOKWPBENZPPME5ZRMZQGGLRS"
display_decimals=4
name="Zam"
desc="Zamzam digital bank 3.0 power by blockchain token"
conditions="There will only ever be 8,500,000,000 Zam tokens in existence."
image="https://zam.io/.well-know/logo.png"
